apiVersion: nodenetwork.openshift.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: policy
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  priority: 99
  desiredState:
    interfaces: 
    - name: eth1
      numVfs: 2
