---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodenetworkconfigurationpolicies.nodenetwork.openshift.io
spec:
  group: nodenetwork.openshift.io
  names:
    kind: NodeNetworkConfigurationPolicy
    listKind: NodeNetworkConfigurationPolicyList
    plural: nodenetworkconfigurationpolicies
    singular: nodenetworkconfigurationpolicy
  scope: Cluster
  version: v1alpha1

